//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Gameplay : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.gameplay_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.gameplay_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.gameplay_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.gameplay_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.gameplay_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.gameplay_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.gameplay_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Fire
        {
            get
            {
                return SteamVR_Actions.gameplay_Fire;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.gameplay_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Interact
        {
            get
            {
                return SteamVR_Actions.gameplay_Interact;
            }
        }
        
        public virtual SteamVR_Action_Boolean Reload
        {
            get
            {
                return SteamVR_Actions.gameplay_Reload;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchWeapons
        {
            get
            {
                return SteamVR_Actions.gameplay_SwitchWeapons;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimarySkill
        {
            get
            {
                return SteamVR_Actions.gameplay_PrimarySkill;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondarySkill
        {
            get
            {
                return SteamVR_Actions.gameplay_SecondarySkill;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dash
        {
            get
            {
                return SteamVR_Actions.gameplay_Dash;
            }
        }
        
        public virtual SteamVR_Action_Boolean WeaponSkill
        {
            get
            {
                return SteamVR_Actions.gameplay_WeaponSkill;
            }
        }
        
        public virtual SteamVR_Action_Boolean InterruptCharging
        {
            get
            {
                return SteamVR_Actions.gameplay_InterruptCharging;
            }
        }
        
        public virtual SteamVR_Action_Boolean DualWielding
        {
            get
            {
                return SteamVR_Actions.gameplay_DualWielding;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchFireMode
        {
            get
            {
                return SteamVR_Actions.gameplay_SwitchFireMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeamInformation
        {
            get
            {
                return SteamVR_Actions.gameplay_TeamInformation;
            }
        }
        
        public virtual SteamVR_Action_Boolean Ping
        {
            get
            {
                return SteamVR_Actions.gameplay_Ping;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Rotate
        {
            get
            {
                return SteamVR_Actions.gameplay_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.gameplay_Haptic;
            }
        }
    }
}
