//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_Gameplay p_Gameplay;
        
        public static SteamVR_Input_ActionSet_Gameplay Gameplay
        {
            get
            {
                return SteamVR_Actions.p_Gameplay.GetCopy<SteamVR_Input_ActionSet_Gameplay>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_Gameplay = ((SteamVR_Input_ActionSet_Gameplay)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Gameplay>("/actions/Gameplay")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.Gameplay};
        }
    }
}
